[build]
  # Build command for the application
  command = "node deployment/scripts/build-netlify.js && npm run build"
  
  # Directory to publish (where the built files are located)
  publish = "app/public"
  
  # Base directory for the build
  base = "."
  
  # Environment variables for build
  [build.environment]
    NODE_VERSION = "18"
    NPM_VERSION = "9"
    NODE_ENV = "production"

# Redirect rules for SPA routing
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com; font-src 'self' https://cdnjs.cloudflare.com; img-src 'self' data:; connect-src 'self' https://cluster0.xxothym.mongodb.net;"

# Function configuration for serverless functions
[functions]
  directory = "deployment/netlify/functions"
  node_bundler = "esbuild"

# Development settings
[dev]
  command = "npm run dev"
  port = 3000
  publish = "app/public"
  autoLaunch = false